name: Release
on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@main
        id: semantic
        with:
#          dry_run: true
#          ci: false
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            conventional-changelog-eslint
            semantic-release-major-tag
          branches: |
            ['main']
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
